env:
  es2021: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - prettier
overrides:
  - extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    files:
      - '*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
    plugins:
      - '@typescript-eslint'
    rules:
      '@typescript-eslint/member-ordering':
        - error
        - default:
            - signature
            - field
            - method
          classes:
            - public-static-field
            - public-instance-method
      '@typescript-eslint/no-implied-eval': off
      '@typescript-eslint/no-unsafe-assignment': off
      '@typescript-eslint/no-unsafe-call': off
      '@typescript-eslint/no-unsafe-member-access': off
      '@typescript-eslint/no-unsafe-return': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/unbound-method': off
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - prettier
  - simple-import-sort
rules:
  linebreak-style:
    - error
    - unix
  no-template-curly-in-string: error
  prefer-template: error
  prettier/prettier: error
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  sort-imports: off
  sort-keys: error
root: true
